"""
Text Detection & Line Segmentation
Primary:  CRAFT (persistent singleton, loaded once)
Fallback: Overlap-aware projection profiling with morphological seam separation
Optional: U-Net pixel-level line segmentation (set cfg.detection.use_unet=True)

Difficulty tagging
------------------
Each TextLine is tagged "clean" or "hard" based on local ink-density variance
in the crop. High variance = overlapping strokes bleeding from adjacent lines.
This tag flows through the pipeline to the evaluator for per-difficulty CER/WER.
"""

import numpy as np
import cv2
from dataclasses import dataclass, field
from PIL import Image
from config.settings import cfg
from ocr.utils.logger import get_logger

log = get_logger(__name__)
C = cfg.detection


@dataclass
class TextLine:
    bbox: tuple[int, int, int, int]   # (x1, y1, x2, y2)
    crop: np.ndarray                   # cropped binary image
    difficulty_tag: str = "clean"      # "clean" | "hard"


# ── U-Net Line Segmentation ──────────────────────────────────────────────────
# Lightweight encoder-decoder that outputs a per-pixel line-instance mask.
# Each output channel = one text line. Trained on synthetic page images with
# overlapping ascenders/descenders (generated by ocr/augmentation/augmentor.py).
# Falls back to projection profiling when checkpoint is missing.

import torch
import torch.nn as nn


class _DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.net(x)


class LineSegUNet(nn.Module):
    """
    Lightweight U-Net for pixel-level text-line segmentation.
    Input:  (1, H, W) grayscale page image (H = cfg.detection.unet_input_height)
    Output: (1, H, W) soft mask in [0,1]; threshold at 0.5 to get binary line mask.

    Training target: binary mask where each text-line region = 1, gaps = 0.
    The model learns to separate overlapping ascender/descender regions by
    context (surrounding strokes) rather than just horizontal projection.

    To train: see scripts/train_unet.py
    """
    def __init__(self, base_ch: int = 32):
        super().__init__()
        # Encoder
        self.enc1 = _DoubleConv(1, base_ch)
        self.enc2 = _DoubleConv(base_ch, base_ch * 2)
        self.enc3 = _DoubleConv(base_ch * 2, base_ch * 4)
        self.pool = nn.MaxPool2d(2)
        # Bottleneck
        self.bottleneck = _DoubleConv(base_ch * 4, base_ch * 8)
        # Decoder
        self.up3 = nn.ConvTranspose2d(base_ch * 8, base_ch * 4, 2, stride=2)
        self.dec3 = _DoubleConv(base_ch * 8, base_ch * 4)
        self.up2 = nn.ConvTranspose2d(base_ch * 4, base_ch * 2, 2, stride=2)
        self.dec2 = _DoubleConv(base_ch * 4, base_ch * 2)
        self.up1 = nn.ConvTranspose2d(base_ch * 2, base_ch, 2, stride=2)
        self.dec1 = _DoubleConv(base_ch * 2, base_ch)
        self.out_conv = nn.Conv2d(base_ch, 1, 1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        b  = self.bottleneck(self.pool(e3))
        d3 = self.dec3(torch.cat([self.up3(b),  e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))
        return torch.sigmoid(self.out_conv(d1))


_unet: LineSegUNet | None = None


def _get_unet() -> LineSegUNet | None:
    global _unet
    if _unet is not None:
        return _unet
    if not C.use_unet:
        return None
    from pathlib import Path
    ckpt = Path(C.unet_checkpoint)
    if not ckpt.exists():
        log.warning("U-Net checkpoint not found at '%s' — using projection fallback", ckpt)
        return None
    device = "cuda" if torch.cuda.is_available() else "cpu"
    _unet = LineSegUNet()
    _unet.load_state_dict(torch.load(str(ckpt), map_location=device, weights_only=True))
    _unet.to(device).eval()
    log.info("U-Net line segmentation model loaded from %s", ckpt)
    return _unet


@torch.inference_mode()
def _unet_detect(binary: np.ndarray) -> list[tuple]:
    """
    Run U-Net on the full page binary image.
    Returns line bounding boxes extracted from the predicted mask.
    """
    unet = _get_unet()
    if unet is None:
        return []

    device = next(unet.parameters()).device
    h_orig, w_orig = binary.shape
    target_h = C.unet_input_height
    scale = target_h / h_orig
    target_w = int(w_orig * scale)

    resized = cv2.resize(binary, (target_w, target_h), interpolation=cv2.INTER_LINEAR)
    tensor = torch.from_numpy(resized).float().unsqueeze(0).unsqueeze(0) / 255.0
    tensor = tensor.to(device)

    mask = unet(tensor)[0, 0].cpu().numpy()  # (H, W) in [0,1]
    binary_mask = (mask > 0.5).astype(np.uint8) * 255

    # Scale mask back to original resolution
    binary_mask = cv2.resize(binary_mask, (w_orig, h_orig), interpolation=cv2.INTER_NEAREST)

    # Extract connected line regions from mask
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(
        binary_mask, connectivity=8
    )
    boxes = []
    for lbl in range(1, num_labels):
        x = stats[lbl, cv2.CC_STAT_LEFT]
        y = stats[lbl, cv2.CC_STAT_TOP]
        w = stats[lbl, cv2.CC_STAT_WIDTH]
        h = stats[lbl, cv2.CC_STAT_HEIGHT]
        if h >= C.min_line_height and w >= C.min_line_width:
            boxes.append((x, y, x + w, y + h))
    return sorted(boxes, key=lambda b: b[1])


# ── Difficulty tagging ────────────────────────────────────────────────────────

def _tag_difficulty(crop: np.ndarray) -> str:
    """
    Classify a line crop as "hard" or "clean" based on local ink-density variance.

    Rationale: overlapping ascenders/descenders create high local variance in
    the horizontal ink projection — some columns have dense crossing strokes,
    others have gaps. Clean lines have a smoother, more uniform projection.

    Threshold tuned empirically; adjust cfg.detection.overlap_variance_threshold.
    """
    if crop is None or crop.size == 0:
        return "clean"
    ink_col = np.sum(crop == 0, axis=0).astype(float)  # ink per column
    if ink_col.max() == 0:
        return "clean"
    ink_col /= ink_col.max()  # normalise to [0,1]
    variance = float(np.var(ink_col))
    return "hard" if variance > C.overlap_variance_threshold else "clean"


# ── CRAFT Singleton ───────────────────────────────────────────────────────────

_craft = None

def _get_craft():
    global _craft
    if _craft is not None:
        return _craft
    if not C.use_craft:
        return None
    try:
        from craft_text_detector import Craft
        _craft = Craft(output_dir=None, crop_type="box", cuda=False)
        log.info("CRAFT model loaded")
        return _craft
    except Exception as e:
        log.warning("CRAFT unavailable (%s) — using projection profiling", e)
        return None


def _craft_detect(bgr: np.ndarray) -> list[tuple]:
    craft = _get_craft()
    if craft is None:
        return []
    try:
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        result = craft.detect_text(rgb)
        boxes = []
        for box in result["boxes"]:
            pts = np.array(box, dtype=np.int32)
            boxes.append((
                int(pts[:, 0].min()), int(pts[:, 1].min()),
                int(pts[:, 0].max()), int(pts[:, 1].max()),
            ))
        return sorted(boxes, key=lambda b: (b[1], b[0]))
    except Exception as e:
        log.warning("CRAFT inference failed: %s", e)
        return []


# ── Projection Profiling (overlap-aware) ─────────────────────────────────────

def _smooth(arr: np.ndarray, window: int) -> np.ndarray:
    """1-D Gaussian smoothing via convolution."""
    if window < 3:
        return arr
    kernel = np.exp(-0.5 * (np.arange(window) - window // 2) ** 2 / (window / 4) ** 2)
    kernel /= kernel.sum()
    return np.convolve(arr, kernel, mode="same")


def _find_valley_cuts(projection: np.ndarray, min_px: int) -> list[int]:
    """
    Find row indices that are local minima (valleys) in the projection profile.
    Uses smoothed profile to avoid splitting at ascender/descender dips.
    Returns sorted list of cut rows.
    """
    smoothed = _smooth(projection.astype(float), C.overlap_valley_smooth)
    peak = smoothed.max()
    if peak == 0:
        return []
    threshold = peak * C.overlap_min_valley_depth

    cuts = []
    in_valley = False
    valley_start = 0
    for i, v in enumerate(smoothed):
        if not in_valley and v < threshold:
            in_valley = True
            valley_start = i
        elif in_valley and v >= threshold:
            in_valley = False
            cuts.append((valley_start + i) // 2)  # midpoint of valley
    return cuts


def _seam_separate_overlap(binary: np.ndarray, y_cut: int) -> int:
    """
    Refine a horizontal cut line using morphological seam analysis.
    Looks in a ±seam_iterations pixel band around y_cut and finds the row
    with the fewest dark pixels (minimum ink crossing) — the true gap.
    """
    half = C.overlap_seam_iterations
    y1 = max(0, y_cut - half)
    y2 = min(binary.shape[0], y_cut + half + 1)
    band = binary[y1:y2, :]
    ink_per_row = np.sum(band == 0, axis=1)
    best_offset = int(np.argmin(ink_per_row))
    return y1 + best_offset


def _projection_detect(binary: np.ndarray) -> list[tuple]:
    h, w = binary.shape
    projection = np.sum(binary == 0, axis=1).astype(float)
    min_px = max(3, int(w * C.projection_min_pixel_ratio))

    cuts = _find_valley_cuts(projection, min_px)
    # Refine each cut with seam analysis to handle overlapping strokes
    refined_cuts = [_seam_separate_overlap(binary, c) for c in cuts]
    refined_cuts = sorted(set(refined_cuts))

    # Build line boxes from refined cuts
    boundaries = [0] + refined_cuts + [h]
    boxes = []
    for i in range(len(boundaries) - 1):
        y1, y2 = boundaries[i], boundaries[i + 1]
        if y2 - y1 < C.min_line_height:
            continue
        # Check there's actual ink in this band
        if np.sum(binary[y1:y2, :] == 0) < min_px:
            continue
        boxes.append((0, y1, w, y2))
    return boxes


def _reassign_bleed_components(binary: np.ndarray, line_boxes: list[tuple]) -> list[tuple]:
    """
    Connected-component analysis: components whose centroid falls between two
    line bands (ascender/descender bleed) are re-assigned to the nearest line
    by vertical centroid distance, then the bounding boxes are updated.
    """
    if len(line_boxes) < 2:
        return line_boxes

    page_h, page_w = binary.shape
    median_line_h = float(np.median([b[3] - b[1] for b in line_boxes]))
    max_component_h = max(C.min_line_height, median_line_h * 2.5)
    max_component_w = page_w * 0.80

    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(
        (binary == 0).astype(np.uint8), connectivity=8
    )

    # Compute line center rows
    line_centers = [(b[1] + b[3]) / 2 for b in line_boxes]
    adjusted = [list(b) for b in line_boxes]  # mutable copy

    for lbl in range(1, num_labels):
        comp_x = stats[lbl, cv2.CC_STAT_LEFT]
        comp_y1 = stats[lbl, cv2.CC_STAT_TOP]
        comp_w = stats[lbl, cv2.CC_STAT_WIDTH]
        comp_h = stats[lbl, cv2.CC_STAT_HEIGHT]
        comp_area = stats[lbl, cv2.CC_STAT_AREA]

        # Ignore borders, shadows, ruling remnants, and thresholding artifacts.
        # A genuine ascender/descender bleed component is local; it should not
        # span most of the page or dwarf the normal line height.
        touches_page_edge = (
            comp_x <= 1 or comp_y1 <= 1
            or comp_x + comp_w >= page_w - 1
            or comp_y1 + comp_h >= page_h - 1
        )
        if comp_h > max_component_h or comp_w > max_component_w:
            continue
        if touches_page_edge and comp_area > page_w * 0.02:
            continue

        cy = centroids[lbl][1]
        # Find which line this component's centroid is closest to
        nearest = int(np.argmin([abs(cy - lc) for lc in line_centers]))
        comp_y2 = comp_y1 + comp_h

        # Only allow modest expansion around the original band. This prevents
        # distant noise from pulling a crop into neighboring lines.
        _, orig_y1, _, orig_y2 = line_boxes[nearest]
        expansion_limit = max(C.line_padding * 3, int(median_line_h * 0.35))
        if comp_y2 < orig_y1 - expansion_limit or comp_y1 > orig_y2 + expansion_limit:
            continue

        # Expand that line's bbox to include this component
        adjusted[nearest][1] = min(adjusted[nearest][1], comp_y1)
        adjusted[nearest][3] = max(adjusted[nearest][3], comp_y2)

    return [tuple(b) for b in adjusted]


def _tighten_box_to_ink(binary: np.ndarray, box: tuple[int, int, int, int]) -> tuple[int, int, int, int]:
    """
    Shrink a line box to the ink extents inside its band.

    Projection fallback boxes intentionally cover the full page width. Passing
    those extreme aspect-ratio crops to TrOCR can squash the handwriting during
    resizing, so tighten horizontally and vertically before final padding.
    """
    x1, y1, x2, y2 = [int(v) for v in box]
    band = binary[y1:y2, x1:x2]
    if band.size == 0:
        return x1, y1, x2, y2

    ys, xs = np.where(band == 0)
    if len(xs) == 0 or len(ys) == 0:
        return x1, y1, x2, y2

    return (
        x1 + int(xs.min()),
        y1 + int(ys.min()),
        x1 + int(xs.max()) + 1,
        y1 + int(ys.max()) + 1,
    )


# ── Word → Line Grouping ──────────────────────────────────────────────────────

def _merge(boxes: list[tuple]) -> tuple:
    return (min(b[0] for b in boxes), min(b[1] for b in boxes),
            max(b[2] for b in boxes), max(b[3] for b in boxes))


def _group_into_lines(word_boxes: list[tuple]) -> list[tuple]:
    if not word_boxes:
        return []
    lines: list[list[tuple]] = []
    for box in sorted(word_boxes, key=lambda b: b[1]):
        x1, y1, x2, y2 = box
        bh = max(1, y2 - y1)
        placed = False
        for line in lines:
            _, ly1, _, ly2 = _merge(line)
            lh = max(1, ly2 - ly1)
            if min(y2, ly2) - max(y1, ly1) > C.word_overlap_threshold * min(bh, lh):
                line.append(box)
                placed = True
                break
        if not placed:
            lines.append([box])
    return sorted([_merge(ln) for ln in lines], key=lambda b: b[1])


# ── Hierarchical Word→Line Detection ────────────────────────────────────────

def detect_words_hierarchical(bgr: np.ndarray, pil_img: Image.Image) -> list[TextLine]:
    """
    Hierarchical word-and-line detection pipeline.

    Detects individual word bounding boxes, groups them into lines via
    spatial Y-centroid clustering, and returns one TextLine per group.

    Each line crop is built by stitching the individual rotated word crops
    (colour → grayscale) horizontally with a small gap, giving TrOCR a
    clean, axis-aligned strip instead of a wide noisy merged bbox.

    Args:
        bgr:     BGR uint8 image.
        pil_img: PIL RGB image (for WordDetector).

    Returns:
        List of :class:`TextLine` objects sorted top-to-bottom.
    """
    from ocr.detection.word_detector import WordDetector
    from ocr.detection.line_grouper import SpatialLineGrouper
    from PIL import Image as _PILImage

    detector = WordDetector()
    grouper  = SpatialLineGrouper(overlap_ratio=0.6)   # centroid-distance ratio

    word_regions = detector.detect(pil_img)
    if not word_regions:
        log.warning("Hierarchical detector: no words found — falling back.")
        return []

    line_groups = grouper.group(word_regions)
    if not line_groups:
        return []

    h_img, w_img = bgr.shape[:2]
    lines: list[TextLine] = []
    word_gap = 8   # pixels between stitched word crops

    for grp in line_groups:
        # Stitch rotated word crops horizontally → one clean line strip
        crops = [w.crop_pil.convert("L") for w in grp.words]
        if not crops:
            continue

        line_h = max(c.height for c in crops)
        total_w = sum(c.width for c in crops) + word_gap * (len(crops) - 1)
        strip = _PILImage.new("L", (total_w, line_h), color=255)
        x_off = 0
        for crop in crops:
            # Pad crop to line_h vertically (centre it)
            pad_top = (line_h - crop.height) // 2
            strip.paste(crop, (x_off, pad_top))
            x_off += crop.width + word_gap

        strip_np = np.array(strip)
        if strip_np.shape[0] < C.min_line_height or strip_np.shape[1] < C.min_line_width:
            continue

        tag = _tag_difficulty(strip_np)
        lines.append(TextLine(
            bbox=grp.bbox,
            crop=strip_np,
            difficulty_tag=tag,
        ))

    hard = sum(1 for ln in lines if ln.difficulty_tag == "hard")
    log.info(
        "Hierarchical: %d word groups → %d lines (%d hard / %d clean).",
        len(line_groups), len(lines), hard, len(lines) - hard,
    )
    return lines


# ── Step 3: Line-merge verification ────────────────────────────────────────────

def verify_line_segmentation(
    binary: np.ndarray,
    detected_lines: list,
    smooth_window: int = 11,
    merge_height_ratio: float = 1.8,
) -> dict:
    """
    Verify detected line count against a projection-peak estimate and
    identify crops that are suspiciously tall (likely merged lines).

    Two checks:
      1. Peak-count check — counts peaks in the smoothed horizontal ink
         projection of the full page.  Each peak = one text line.  If the
         detected line count is less than 70% of the peak count, lines were
         likely merged.
      2. Height-ratio check — any crop whose height exceeds
         ``merge_height_ratio * median_line_height`` is flagged as a
         probable merged crop, with its pixel range logged.

    Args:
        binary:             Binarised page image (0=ink, 255=background).
        detected_lines:     List of :class:`TextLine` objects from detect_lines.
        smooth_window:      Gaussian smoothing window for projection (px).
        merge_height_ratio: Crops taller than this multiple of the median
                            line height are flagged as merged.

    Returns:
        dict with keys:
          ``peak_estimate``   – int, projection-based line count estimate
          ``detected_count``  – int, number of detected lines
          ``merged_crops``    – list of dicts {index, bbox, height, y_ranges}
                               for each suspected merged crop
          ``warning``         – str or None, human-readable summary
    """
    if not detected_lines:
        return {"peak_estimate": 0, "detected_count": 0,
                "merged_crops": [], "warning": "No lines detected."}

    # ── Check 1: projection peak count ───────────────────────────────────────
    projection = np.sum(binary == 0, axis=1).astype(float)
    smoothed   = _smooth(projection, smooth_window)
    peak_val   = smoothed.max()
    if peak_val == 0:
        peak_estimate = 0
    else:
        # A peak is a local maximum above 15% of the global max
        peak_threshold = peak_val * 0.15
        above = smoothed > peak_threshold
        peak_estimate = 0
        in_peak = False
        for v in above:
            if v and not in_peak:
                peak_estimate += 1
                in_peak = True
            elif not v:
                in_peak = False

    detected_count = len(detected_lines)

    # ── Check 2: height-ratio merge detection ───────────────────────────────
    heights = [ln.bbox[3] - ln.bbox[1] for ln in detected_lines]
    median_h = float(np.median(heights))
    merge_threshold = median_h * merge_height_ratio

    merged_crops = []
    for idx, ln in enumerate(detected_lines):
        x1, y1, x2, y2 = ln.bbox
        h = y2 - y1
        if h > merge_threshold:
            # Estimate where the internal line boundary likely is
            # by finding the row with minimum ink inside this crop
            crop_proj = np.sum(binary[y1:y2, :] == 0, axis=1).astype(float)
            if len(crop_proj) > 4:
                # Smooth and find the valley (minimum) in the middle half
                mid_start = len(crop_proj) // 4
                mid_end   = 3 * len(crop_proj) // 4
                mid_proj  = crop_proj[mid_start:mid_end]
                valley_offset = int(np.argmin(mid_proj)) + mid_start
                split_y = y1 + valley_offset
                y_ranges = [(y1, split_y), (split_y, y2)]
            else:
                y_ranges = [(y1, y2)]

            merged_crops.append({
                "index":   idx,
                "bbox":    tuple(int(v) for v in ln.bbox),
                "height":  int(h),
                "y_ranges": [(int(a), int(b)) for a, b in y_ranges],
            })
            log.warning(
                "Possible merged crop at line %d: height=%dpx (%.1fx median=%.0fpx) "
                "bbox=%s  estimated split at y=%s",
                idx, h, h / median_h, median_h,
                tuple(int(v) for v in ln.bbox),
                [int(r[0]) for r in y_ranges[1:]],
            )

    # ── Summary warning ────────────────────────────────────────────────────────
    warning = None
    issues = []
    if peak_estimate > 0 and detected_count < peak_estimate * 0.70:
        issues.append(
            f"detected {detected_count} lines but projection suggests "
            f"~{peak_estimate} — {peak_estimate - detected_count} lines may be merged"
        )
    if merged_crops:
        issues.append(
            f"{len(merged_crops)} crop(s) are >{merge_height_ratio:.1f}x median height "
            f"({median_h:.0f}px) — likely merged text rows"
        )
    if issues:
        warning = "Line segmentation warning: " + "; ".join(issues)
        log.warning(warning)

    return {
        "peak_estimate":  peak_estimate,
        "detected_count": detected_count,
        "merged_crops":   merged_crops,
        "warning":        warning,
    }


# ── Main Entry ────────────────────────────────────────────────────────────────

def detect_lines(binary: np.ndarray, bgr: np.ndarray) -> list[TextLine]:
    """
    Detect text lines. Priority: U-Net > CRAFT > projection profiling.
    Each TextLine is tagged with a difficulty_tag ("clean" | "hard").
    """
    # Try U-Net first (best for overlapping lines)
    line_boxes = _unet_detect(binary)
    if line_boxes:
        log.debug("U-Net detected %d lines", len(line_boxes))
    else:
        # Try CRAFT
        word_boxes = _craft_detect(bgr)
        if word_boxes:
            line_boxes = _group_into_lines(word_boxes)
            log.debug("CRAFT detected %d word boxes -> %d lines",
                      len(word_boxes), len(line_boxes))
        else:
            # Projection profiling fallback
            line_boxes = _projection_detect(binary)
            line_boxes = _reassign_bleed_components(binary, line_boxes)
            log.debug("Projection (overlap-aware) detected %d lines", len(line_boxes))

    h, w = binary.shape
    p = C.line_padding
    lines = []
    for (x1, y1, x2, y2) in line_boxes:
        x1, y1, x2, y2 = _tighten_box_to_ink(binary, (x1, y1, x2, y2))
        x1c, y1c = max(0, x1 - p), max(0, y1 - p)
        x2c, y2c = min(w, x2 + p), min(h, y2 + p)
        binary_crop = binary[y1c:y2c, x1c:x2c]
        # TrOCR performs better on natural grayscale/color handwriting than on
        # hard-thresholded binary crops, especially for photographed notebook
        # pages. Keep binary for detection and difficulty tagging, but return
        # the aligned source crop for recognition.
        crop = bgr[y1c:y2c, x1c:x2c] if bgr.shape[:2] == binary.shape else binary_crop
        if binary_crop.shape[0] >= C.min_line_height and binary_crop.shape[1] >= C.min_line_width:
            tag = _tag_difficulty(binary_crop)
            lines.append(TextLine(bbox=(x1c, y1c, x2c, y2c), crop=crop,
                                  difficulty_tag=tag))

    hard_count = sum(1 for ln in lines if ln.difficulty_tag == "hard")
    log.info("Segmented %d lines (%d hard / %d clean)",
             len(lines), hard_count, len(lines) - hard_count)

    # Step 3: verify segmentation and warn about merged crops
    verify_line_segmentation(binary, lines)

    return lines
