"""
Text Detection & Line Segmentation
Primary:  CRAFT (persistent singleton, loaded once)
Fallback: Overlap-aware projection profiling with morphological seam separation
Optional: U-Net pixel-level line segmentation (set cfg.detection.use_unet=True)

Difficulty tagging
------------------
Each TextLine is tagged "clean" or "hard" based on local ink-density variance
in the crop. High variance = overlapping strokes bleeding from adjacent lines.
This tag flows through the pipeline to the evaluator for per-difficulty CER/WER.
"""

import numpy as np
import cv2
from dataclasses import dataclass, field
from PIL import Image
from config.settings import cfg
from ocr.utils.logger import get_logger

log = get_logger(__name__)
C = cfg.detection


@dataclass
class TextLine:
    bbox: tuple[int, int, int, int]   # (x1, y1, x2, y2)
    crop: np.ndarray                   # cropped binary image
    difficulty_tag: str = "clean"      # "clean" | "hard"


# ── U-Net Line Segmentation ──────────────────────────────────────────────────
# Lightweight encoder-decoder that outputs a per-pixel line-instance mask.
# Each output channel = one text line. Trained on synthetic page images with
# overlapping ascenders/descenders (generated by ocr/augmentation/augmentor.py).
# Falls back to projection profiling when checkpoint is missing.

import torch
import torch.nn as nn


class _DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.net(x)


class LineSegUNet(nn.Module):
    """
    Lightweight U-Net for pixel-level text-line segmentation.
    Input:  (1, H, W) grayscale page image (H = cfg.detection.unet_input_height)
    Output: (1, H, W) soft mask in [0,1]; threshold at 0.5 to get binary line mask.

    Training target: binary mask where each text-line region = 1, gaps = 0.
    The model learns to separate overlapping ascender/descender regions by
    context (surrounding strokes) rather than just horizontal projection.

    To train: see scripts/train_unet.py
    """
    def __init__(self, base_ch: int = 32):
        super().__init__()
        # Encoder
        self.enc1 = _DoubleConv(1, base_ch)
        self.enc2 = _DoubleConv(base_ch, base_ch * 2)
        self.enc3 = _DoubleConv(base_ch * 2, base_ch * 4)
        self.pool = nn.MaxPool2d(2)
        # Bottleneck
        self.bottleneck = _DoubleConv(base_ch * 4, base_ch * 8)
        # Decoder
        self.up3 = nn.ConvTranspose2d(base_ch * 8, base_ch * 4, 2, stride=2)
        self.dec3 = _DoubleConv(base_ch * 8, base_ch * 4)
        self.up2 = nn.ConvTranspose2d(base_ch * 4, base_ch * 2, 2, stride=2)
        self.dec2 = _DoubleConv(base_ch * 4, base_ch * 2)
        self.up1 = nn.ConvTranspose2d(base_ch * 2, base_ch, 2, stride=2)
        self.dec1 = _DoubleConv(base_ch * 2, base_ch)
        self.out_conv = nn.Conv2d(base_ch, 1, 1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        b  = self.bottleneck(self.pool(e3))
        d3 = self.dec3(torch.cat([self.up3(b),  e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))
        return torch.sigmoid(self.out_conv(d1))


_unet: LineSegUNet | None = None


def _get_unet() -> LineSegUNet | None:
    global _unet
    if _unet is not None:
        return _unet
    if not C.use_unet:
        return None
    from pathlib import Path
    ckpt = Path(C.unet_checkpoint)
    if not ckpt.exists():
        log.warning("U-Net checkpoint not found at '%s' — using projection fallback", ckpt)
        return None
    device = "cuda" if torch.cuda.is_available() else "cpu"
    _unet = LineSegUNet()
    _unet.load_state_dict(torch.load(str(ckpt), map_location=device, weights_only=True))
    _unet.to(device).eval()
    log.info("U-Net line segmentation model loaded from %s", ckpt)
    return _unet


@torch.inference_mode()
def _unet_detect(binary: np.ndarray) -> list[tuple]:
    """
    Run U-Net on the full page binary image.
    Returns line bounding boxes extracted from the predicted mask.
    """
    unet = _get_unet()
    if unet is None:
        return []

    device = next(unet.parameters()).device
    h_orig, w_orig = binary.shape
    target_h = C.unet_input_height
    scale = target_h / h_orig
    target_w = int(w_orig * scale)

    resized = cv2.resize(binary, (target_w, target_h), interpolation=cv2.INTER_LINEAR)
    tensor = torch.from_numpy(resized).float().unsqueeze(0).unsqueeze(0) / 255.0
    tensor = tensor.to(device)

    mask = unet(tensor)[0, 0].cpu().numpy()  # (H, W) in [0,1]
    binary_mask = (mask > 0.5).astype(np.uint8) * 255

    # Scale mask back to original resolution
    binary_mask = cv2.resize(binary_mask, (w_orig, h_orig), interpolation=cv2.INTER_NEAREST)

    # Extract connected line regions from mask
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(
        binary_mask, connectivity=8
    )
    boxes = []
    for lbl in range(1, num_labels):
        x = stats[lbl, cv2.CC_STAT_LEFT]
        y = stats[lbl, cv2.CC_STAT_TOP]
        w = stats[lbl, cv2.CC_STAT_WIDTH]
        h = stats[lbl, cv2.CC_STAT_HEIGHT]
        if h >= C.min_line_height and w >= C.min_line_width:
            boxes.append((x, y, x + w, y + h))
    return sorted(boxes, key=lambda b: b[1])


# ── Difficulty tagging ────────────────────────────────────────────────────────

def _tag_difficulty(crop: np.ndarray) -> str:
    """
    Classify a line crop as "hard" or "clean" based on local ink-density variance.

    Rationale: overlapping ascenders/descenders create high local variance in
    the horizontal ink projection — some columns have dense crossing strokes,
    others have gaps. Clean lines have a smoother, more uniform projection.

    Threshold tuned empirically; adjust cfg.detection.overlap_variance_threshold.
    """
    if crop is None or crop.size == 0:
        return "clean"
    ink_col = np.sum(crop == 0, axis=0).astype(float)  # ink per column
    if ink_col.max() == 0:
        return "clean"
    ink_col /= ink_col.max()  # normalise to [0,1]
    variance = float(np.var(ink_col))
    return "hard" if variance > C.overlap_variance_threshold else "clean"


# ── CRAFT Singleton ───────────────────────────────────────────────────────────

_craft = None

def _get_craft():
    global _craft
    if _craft is not None:
        return _craft
    if not C.use_craft:
        return None
    try:
        from craft_text_detector import Craft
        _craft = Craft(output_dir=None, crop_type="box", cuda=False)
        log.info("CRAFT model loaded")
        return _craft
    except Exception as e:
        log.warning("CRAFT unavailable (%s) — using projection profiling", e)
        return None


def _craft_detect(bgr: np.ndarray) -> list[tuple]:
    craft = _get_craft()
    if craft is None:
        return []
    try:
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        result = craft.detect_text(rgb)
        boxes = []
        for box in result["boxes"]:
            pts = np.array(box, dtype=np.int32)
            boxes.append((
                int(pts[:, 0].min()), int(pts[:, 1].min()),
                int(pts[:, 0].max()), int(pts[:, 1].max()),
            ))
        return sorted(boxes, key=lambda b: (b[1], b[0]))
    except Exception as e:
        log.warning("CRAFT inference failed: %s", e)
        return []


# ── Projection Profiling (overlap-aware) ─────────────────────────────────────

def _smooth(arr: np.ndarray, window: int) -> np.ndarray:
    """1-D Gaussian smoothing via convolution."""
    if window < 3:
        return arr
    kernel = np.exp(-0.5 * (np.arange(window) - window // 2) ** 2 / (window / 4) ** 2)
    kernel /= kernel.sum()
    return np.convolve(arr, kernel, mode="same")


def _find_valley_cuts(projection: np.ndarray, min_px: int) -> list[int]:
    """
    Find row indices that are local minima (valleys) in the projection profile.
    Uses smoothed profile to avoid splitting at ascender/descender dips.
    Returns sorted list of cut rows.
    """
    smoothed = _smooth(projection.astype(float), C.overlap_valley_smooth)
    peak = smoothed.max()
    if peak == 0:
        return []
    threshold = peak * C.overlap_min_valley_depth

    cuts = []
    in_valley = False
    valley_start = 0
    for i, v in enumerate(smoothed):
        if not in_valley and v < threshold:
            in_valley = True
            valley_start = i
        elif in_valley and v >= threshold:
            in_valley = False
            cuts.append((valley_start + i) // 2)  # midpoint of valley
    return cuts


def _seam_separate_overlap(binary: np.ndarray, y_cut: int) -> int:
    """
    Refine a horizontal cut line using morphological seam analysis.
    Looks in a ±seam_iterations pixel band around y_cut and finds the row
    with the fewest dark pixels (minimum ink crossing) — the true gap.
    """
    half = C.overlap_seam_iterations
    y1 = max(0, y_cut - half)
    y2 = min(binary.shape[0], y_cut + half + 1)
    band = binary[y1:y2, :]
    ink_per_row = np.sum(band == 0, axis=1)
    best_offset = int(np.argmin(ink_per_row))
    return y1 + best_offset


def _projection_detect(binary: np.ndarray) -> list[tuple]:
    h, w = binary.shape
    projection = np.sum(binary == 0, axis=1).astype(float)
    min_px = max(3, int(w * C.projection_min_pixel_ratio))

    cuts = _find_valley_cuts(projection, min_px)
    # Refine each cut with seam analysis to handle overlapping strokes
    refined_cuts = [_seam_separate_overlap(binary, c) for c in cuts]
    refined_cuts = sorted(set(refined_cuts))

    # Build line boxes from refined cuts
    boundaries = [0] + refined_cuts + [h]
    boxes = []
    for i in range(len(boundaries) - 1):
        y1, y2 = boundaries[i], boundaries[i + 1]
        if y2 - y1 < C.min_line_height:
            continue
        # Check there's actual ink in this band
        if np.sum(binary[y1:y2, :] == 0) < min_px:
            continue
        boxes.append((0, y1, w, y2))
    return boxes


def _reassign_bleed_components(binary: np.ndarray, line_boxes: list[tuple]) -> list[tuple]:
    """
    Connected-component analysis: components whose centroid falls between two
    line bands (ascender/descender bleed) are re-assigned to the nearest line
    by vertical centroid distance, then the bounding boxes are updated.
    """
    if len(line_boxes) < 2:
        return line_boxes

    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(
        (binary == 0).astype(np.uint8), connectivity=8
    )

    # Compute line center rows
    line_centers = [(b[1] + b[3]) / 2 for b in line_boxes]
    adjusted = [list(b) for b in line_boxes]  # mutable copy

    for lbl in range(1, num_labels):
        cy = centroids[lbl][1]
        # Find which line this component's centroid is closest to
        nearest = int(np.argmin([abs(cy - lc) for lc in line_centers]))
        comp_y1 = stats[lbl, cv2.CC_STAT_TOP]
        comp_y2 = comp_y1 + stats[lbl, cv2.CC_STAT_HEIGHT]
        # Expand that line's bbox to include this component
        adjusted[nearest][1] = min(adjusted[nearest][1], comp_y1)
        adjusted[nearest][3] = max(adjusted[nearest][3], comp_y2)

    return [tuple(b) for b in adjusted]


# ── Word → Line Grouping ──────────────────────────────────────────────────────

def _merge(boxes: list[tuple]) -> tuple:
    return (min(b[0] for b in boxes), min(b[1] for b in boxes),
            max(b[2] for b in boxes), max(b[3] for b in boxes))


def _group_into_lines(word_boxes: list[tuple]) -> list[tuple]:
    if not word_boxes:
        return []
    lines: list[list[tuple]] = []
    for box in sorted(word_boxes, key=lambda b: b[1]):
        x1, y1, x2, y2 = box
        bh = max(1, y2 - y1)
        placed = False
        for line in lines:
            _, ly1, _, ly2 = _merge(line)
            lh = max(1, ly2 - ly1)
            if min(y2, ly2) - max(y1, ly1) > C.word_overlap_threshold * min(bh, lh):
                line.append(box)
                placed = True
                break
        if not placed:
            lines.append([box])
    return sorted([_merge(ln) for ln in lines], key=lambda b: b[1])


# ── Main Entry ────────────────────────────────────────────────────────────────

def detect_lines(binary: np.ndarray, bgr: np.ndarray) -> list[TextLine]:
    """
    Detect text lines. Priority: U-Net > CRAFT > projection profiling.
    Each TextLine is tagged with a difficulty_tag ("clean" | "hard").
    """
    # Try U-Net first (best for overlapping lines)
    line_boxes = _unet_detect(binary)
    if line_boxes:
        log.debug("U-Net detected %d lines", len(line_boxes))
    else:
        # Try CRAFT
        word_boxes = _craft_detect(bgr)
        if word_boxes:
            line_boxes = _group_into_lines(word_boxes)
            log.debug("CRAFT detected %d word boxes -> %d lines",
                      len(word_boxes), len(line_boxes))
        else:
            # Projection profiling fallback
            line_boxes = _projection_detect(binary)
            line_boxes = _reassign_bleed_components(binary, line_boxes)
            log.debug("Projection (overlap-aware) detected %d lines", len(line_boxes))

    h, w = binary.shape
    p = C.line_padding
    lines = []
    for (x1, y1, x2, y2) in line_boxes:
        x1c, y1c = max(0, x1 - p), max(0, y1 - p)
        x2c, y2c = min(w, x2 + p), min(h, y2 + p)
        crop = binary[y1c:y2c, x1c:x2c]
        if crop.shape[0] >= C.min_line_height and crop.shape[1] >= C.min_line_width:
            tag = _tag_difficulty(crop)
            lines.append(TextLine(bbox=(x1c, y1c, x2c, y2c), crop=crop,
                                  difficulty_tag=tag))

    hard_count = sum(1 for ln in lines if ln.difficulty_tag == "hard")
    log.info("Segmented %d lines (%d hard / %d clean)",
             len(lines), hard_count, len(lines) - hard_count)
    return lines
