"""
CRAFT Training Script
=====================
Trains CRAFTDetector on handwritten page images.

Ground-truth generation strategy
---------------------------------
CRAFT originally requires CHARACTER-level bounding box annotations.
Standard handwriting datasets (IAM, RIMES) only provide LINE-level boxes.

We use a weakly-supervised approach:
  1. For each line bounding box, generate a 2D Gaussian heatmap
     centered on the line region.
  2. This Gaussian blob serves as the "character region" ground truth.
  3. The affinity ground truth is generated by connecting adjacent
     Gaussian centers within the same line.

This is an approximation — the model learns to detect line regions
rather than individual characters. For our pipeline this is sufficient
because we only need line-level bounding boxes.

Data format
-----------
data/craft/
    images/
        page_001.jpg
    labels/
        page_001.txt   ← one line per text line: x1,y1,x2,y2

Usage
-----
    python ocr/detection/train_craft.py
    python ocr/detection/train_craft.py --epochs 20 --batch 2

Checkpoint: checkpoints/craft_textdetector.pth

STATUS: IMPLEMENTED, NOT YET TRAINED
"""

import argparse
import time
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split

from ocr.detection.craft import CRAFTDetector
from ocr.utils.logger import get_logger

log = get_logger("train_craft")


# ── Gaussian heatmap generation ───────────────────────────────────────────────

def _gaussian_heatmap(h: int, w: int, bbox, sigma_ratio: float = 0.3) -> np.ndarray:
    """
    Generate a 2D Gaussian heatmap for a single bounding box.

    The Gaussian is centered at the bbox center with sigma proportional
    to the bbox dimensions. This approximates the character region score
    that CRAFT would produce for a line of text.

    Args:
        h, w:        Full image height and width.
        bbox:        (x1, y1, x2, y2) bounding box.
        sigma_ratio: Sigma as fraction of bbox size (default 0.3).

    Returns:
        (h, w) float32 heatmap in [0, 1].
    """
    x1, y1, x2, y2 = bbox
    cx = (x1 + x2) / 2.0
    cy = (y1 + y2) / 2.0
    sigma_x = max(1.0, (x2 - x1) * sigma_ratio)
    sigma_y = max(1.0, (y2 - y1) * sigma_ratio)

    ys, xs = np.mgrid[0:h, 0:w]
    heatmap = np.exp(
        -0.5 * (((xs - cx) / sigma_x) ** 2 + ((ys - cy) / sigma_y) ** 2)
    ).astype(np.float32)
    return heatmap


def _affinity_heatmap(h: int, w: int, bboxes) -> np.ndarray:
    """
    Generate affinity heatmap by placing Gaussians between adjacent line centers.

    For each pair of vertically adjacent lines, place a Gaussian at the
    midpoint between their centers. This teaches CRAFT that adjacent lines
    are related (affinity = they belong to the same document).

    Args:
        h, w:   Image dimensions.
        bboxes: List of (x1, y1, x2, y2) line bounding boxes.

    Returns:
        (h, w) float32 affinity heatmap in [0, 1].
    """
    affinity = np.zeros((h, w), dtype=np.float32)
    if len(bboxes) < 2:
        return affinity

    # Sort by vertical center
    sorted_boxes = sorted(bboxes, key=lambda b: (b[1] + b[3]) / 2)

    for i in range(len(sorted_boxes) - 1):
        b1, b2 = sorted_boxes[i], sorted_boxes[i + 1]
        # Midpoint between centers of adjacent lines
        mid_x = ((b1[0] + b1[2]) / 2 + (b2[0] + b2[2]) / 2) / 2
        mid_y = ((b1[1] + b1[3]) / 2 + (b2[1] + b2[3]) / 2) / 2
        # Sigma based on gap between lines
        gap = abs((b2[1] + b2[3]) / 2 - (b1[1] + b1[3]) / 2)
        sigma = max(5.0, gap * 0.3)

        ys, xs = np.mgrid[0:h, 0:w]
        blob = np.exp(-0.5 * (((xs - mid_x) / sigma) ** 2 +
                               ((ys - mid_y) / sigma) ** 2)).astype(np.float32)
        affinity = np.maximum(affinity, blob)

    return affinity


# ── Dataset ───────────────────────────────────────────────────────────────────

class CRAFTDataset(Dataset):
    """
    Dataset for CRAFT training.

    Loads page images and line-level bounding box annotations.
    Generates character region and affinity heatmaps on the fly.

    Label file format (one line per text line):
        x1,y1,x2,y2
        x1,y1,x2,y2
        ...

    Args:
        images_dir: Path to page images.
        labels_dir: Path to label .txt files (same stem as images).
        input_size: (H, W) to resize images and scale boxes.
    """

    def __init__(self, images_dir: str, labels_dir: str,
                 input_size: tuple = (512, 512)):
        self.images_dir = Path(images_dir)
        self.labels_dir = Path(labels_dir)
        self.input_h, self.input_w = input_size

        exts = {".jpg", ".jpeg", ".png", ".bmp"}
        self.samples = []
        for img_path in sorted(self.images_dir.iterdir()):
            if img_path.suffix.lower() not in exts:
                continue
            lbl_path = self.labels_dir / (img_path.stem + ".txt")
            if lbl_path.exists():
                self.samples.append((img_path, lbl_path))

        if not self.samples:
            raise FileNotFoundError(
                f"No image/label pairs found in {images_dir} / {labels_dir}\n"
                f"Label format: one line per text line, format: x1,y1,x2,y2"
            )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, lbl_path = self.samples[idx]

        # Load image
        img = cv2.imread(str(img_path))
        if img is None:
            raise IOError(f"Cannot read: {img_path}")
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h_orig, w_orig = img.shape[:2]

        # Resize
        img = cv2.resize(img, (self.input_w, self.input_h))
        scale_x = self.input_w / w_orig
        scale_y = self.input_h / h_orig

        # Load and scale bounding boxes
        bboxes = []
        for line in lbl_path.read_text().strip().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                x1, y1, x2, y2 = map(float, line.split(","))
                bboxes.append((
                    int(x1 * scale_x), int(y1 * scale_y),
                    int(x2 * scale_x), int(y2 * scale_y),
                ))
            except ValueError:
                continue

        # Generate heatmaps at half resolution (CRAFT output is H/2, W/2)
        hm_h = self.input_h // 2
        hm_w = self.input_w // 2
        char_map = np.zeros((hm_h, hm_w), dtype=np.float32)
        for bbox in bboxes:
            # Scale bbox to heatmap resolution
            hm_bbox = (bbox[0]//2, bbox[1]//2, bbox[2]//2, bbox[3]//2)
            char_map = np.maximum(char_map,
                                  _gaussian_heatmap(hm_h, hm_w, hm_bbox))

        hm_bboxes = [(b[0]//2, b[1]//2, b[2]//2, b[3]//2) for b in bboxes]
        aff_map = _affinity_heatmap(hm_h, hm_w, hm_bboxes)

        # Normalize image to [0, 1]
        img_tensor = torch.from_numpy(
            img.astype(np.float32) / 255.0
        ).permute(2, 0, 1)  # (3, H, W)

        # Stack heatmaps: (2, H/2, W/2)
        target = torch.from_numpy(
            np.stack([char_map, aff_map], axis=0)
        )

        return img_tensor, target


# ── Loss ──────────────────────────────────────────────────────────────────────

def craft_loss(pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    """
    MSE loss between predicted and target heatmaps.
    Applied separately to character map and affinity map, then summed.

    MSE is appropriate here because both pred and target are continuous
    probability maps in [0, 1], not binary labels.
    """
    char_loss = F.mse_loss(pred[:, 0], target[:, 0])
    aff_loss  = F.mse_loss(pred[:, 1], target[:, 1])
    return char_loss + aff_loss


# ── Training loop ─────────────────────────────────────────────────────────────

def train(args):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    log.info("Device: %s", device)

    try:
        full_ds = CRAFTDataset(
            images_dir=args.images,
            labels_dir=args.labels,
            input_size=(args.height, args.width),
        )
    except FileNotFoundError as e:
        log.error(str(e))
        return

    n_val   = max(1, int(len(full_ds) * 0.15))
    n_train = len(full_ds) - n_val
    train_ds, val_ds = random_split(
        full_ds, [n_train, n_val],
        generator=torch.Generator().manual_seed(42),
    )

    train_loader = DataLoader(train_ds, batch_size=args.batch,
                              shuffle=True, num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch,
                              shuffle=False, num_workers=0)

    log.info("Train: %d | Val: %d", len(train_ds), len(val_ds))

    model = CRAFTDetector().to(device)
    total = sum(p.numel() for p in model.parameters())
    log.info("CRAFTDetector parameters: %d (%.1fM)", total, total / 1e6)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=3
    )

    ckpt_dir = Path("checkpoints")
    ckpt_dir.mkdir(exist_ok=True)
    best_ckpt = ckpt_dir / "craft_textdetector.pth"

    best_val_loss = float("inf")
    patience_counter = 0

    for epoch in range(1, args.epochs + 1):
        model.train()
        train_losses = []
        t0 = time.perf_counter()

        for imgs, targets in train_loader:
            imgs    = imgs.to(device)
            targets = targets.to(device)
            preds   = model(imgs)
            loss    = craft_loss(preds, targets)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            train_losses.append(loss.item())

        model.eval()
        val_losses = []
        with torch.no_grad():
            for imgs, targets in val_loader:
                imgs    = imgs.to(device)
                targets = targets.to(device)
                preds   = model(imgs)
                val_losses.append(craft_loss(preds, targets).item())

        avg_train = float(np.mean(train_losses))
        avg_val   = float(np.mean(val_losses))
        elapsed   = time.perf_counter() - t0

        log.info("Epoch %02d/%02d | train=%.4f | val=%.4f | %.1fs",
                 epoch, args.epochs, avg_train, avg_val, elapsed)

        scheduler.step(avg_val)

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            patience_counter = 0
            torch.save(model.state_dict(), best_ckpt)
            log.info("  ✓ Best CRAFT saved → %s", best_ckpt)
        else:
            patience_counter += 1
            if patience_counter >= args.patience:
                log.info("Early stopping at epoch %d", epoch)
                break

    log.info("CRAFT training complete. Best val=%.4f", best_val_loss)


def parse_args():
    parser = argparse.ArgumentParser(description="Train CRAFT text detector")
    parser.add_argument("--images",   default="data/craft/images")
    parser.add_argument("--labels",   default="data/craft/labels")
    parser.add_argument("--epochs",   type=int,   default=20)
    parser.add_argument("--batch",    type=int,   default=2)
    parser.add_argument("--lr",       type=float, default=1e-4)
    parser.add_argument("--height",   type=int,   default=512)
    parser.add_argument("--width",    type=int,   default=512)
    parser.add_argument("--patience", type=int,   default=5)
    return parser.parse_args()


if __name__ == "__main__":
    train(parse_args())
